In [32]:
help(dm.descriptors.batch_compute_many_descriptors)

Help on function batch_compute_many_descriptors in module datamol.descriptors.compute:

batch_compute_many_descriptors(
    mols: List[Mol],
    properties_fn: Optional[Dict[str, Union[Callable, str]]] = None,
    add_properties: bool = True,
    n_jobs: int = 1,
    batch_size: Optional[int] = None,
    progress: bool = False,
    progress_leave: bool = True
) -> pd.DataFrame
    Compute a list of opiniated molecular properties on a list of molecules.

    Args:
        mols: A list of molecules.
        properties_fn: A list of functions that compute properties. If None,
            a default list of properties is used. If the function is a string,
            `dm.descriptors.any_descriptor()` is used to retrieve the descriptor
            function.
        add_properties: Whether to add the computed properties to the default list.

    Returns:
        A dataframe of computed properties with one row per input molecules.

In [3]:
import pandas as pd
import datamol as dm
from tqdm.auto import tqdm
from rdkit.Chem import rdDepictor
import mols2grid

In [4]:
rdDepictor.SetPreferCoordGen(True)
pd.options.display.float_format = '{:,.2f}'.format

In [5]:
url = "https://raw.githubusercontent.com/PatWalters/yamc/main/data/HERG.smi"
df = pd.read_csv(url,sep=" ",names=["SMILES","Name","pIC50"])

In [6]:
df.head()

                                              SMILES           Name  pIC50
0  c1cc(ccc1n2cc(c3c2ccc(c3)Cl)C4CCN(CC4)CCN5CCNC...    CHEMBL12713   8.03
1  c1ccc2c(c1)[nH]c(=O)n2C3=CCN(CC3)CCCC(=O)c4ccc...     CHEMBL1108   7.33
2    c1ccc2c(c1)c(c[nH]2)C(=O)OC3CC4CC5CC(C3)N4CC5=O  CHEMBL2368925   5.07
3  CC(C)C(CCCN(C)CCc1ccc(c(c1)OC)OC)(C#N)c2ccc(c(...     CHEMBL6966   6.83
4       CCOC(=O)N1CCC(=C2c3ccc(cc3CCc4c2nccc4)Cl)CC1      CHEMBL998   6.43

In [7]:
df['IC50'] = dm.molar.log_to_molar(df.pIC50,'uM')
df.head()

,SMILES,Name,pIC50,IC50
0,c1cc(ccc1n2cc(c3c2ccc(c3)Cl)C4CCN(CC4)CCN5CCNC...,CHEMBL12713,8.03,0.01
1,c1ccc2c(c1)[nH]c(=O)n2C3=CCN(CC3)CCCC(=O)c4ccc...,CHEMBL1108,7.33,0.05
2,c1ccc2c(c1)c(c[nH]2)C(=O)OC3CC4CC5CC(C3)N4CC5=O,CHEMBL2368925,5.07,8.48
3,CC(C)C(CCCN(C)CCc1ccc(c(c1)OC)OC)(C#N)c2ccc(c(...,CHEMBL6966,6.83,0.15
4,CCOC(=O)N1CCC(=C2c3ccc(cc3CCc4c2nccc4)Cl)CC1,CHEMBL998,6.43,0.37

In [8]:
df['mol'] = dm.from_df(df, smiles_column="SMILES")
df.head()

,SMILES,Name,pIC50,IC50,mol
0,c1cc(ccc1n2cc(c3c2ccc(c3)Cl)C4CCN(CC4)CCN5CCNC...,CHEMBL12713,8.03,0.01,<rdkit.Chem.rdchem.Mol object at 0x30c31b5a0>
1,c1ccc2c(c1)[nH]c(=O)n2C3=CCN(CC3)CCCC(=O)c4ccc...,CHEMBL1108,7.33,0.05,<rdkit.Chem.rdchem.Mol object at 0x30c31b610>
2,c1ccc2c(c1)c(c[nH]2)C(=O)OC3CC4CC5CC(C3)N4CC5=O,CHEMBL2368925,5.07,8.48,<rdkit.Chem.rdchem.Mol object at 0x30c31b680>
3,CC(C)C(CCCN(C)CCc1ccc(c(c1)OC)OC)(C#N)c2ccc(c(...,CHEMBL6966,6.83,0.15,<rdkit.Chem.rdchem.Mol object at 0x30c31b6f0>
4,CCOC(=O)N1CCC(=C2c3ccc(cc3CCc4c2nccc4)Cl)CC1,CHEMBL998,6.43,0.37,<rdkit.Chem.rdchem.Mol object at 0x30c31b760>

In [9]:
def max_ring_size(mol):
    """Get the size of the largest ring in a molecule

    :param mol: input_molecule
    :return: size of the largest ring or 0 for an acyclic molecule
    """
    ri = mol.GetRingInfo()
    atom_rings = ri.AtomRings()
    if len(atom_rings) == 0:
        return 0
    else:
        return max([len(x) for x in ri.AtomRings()])

In [10]:
my_prop_dict = {
    "mw" : dm.descriptors.mw,
    "logp" : dm.descriptors.clogp,
    "hbd" : dm.descriptors.n_lipinski_hbd,
    "hba" : dm.descriptors.n_lipinski_hba,
    "max_ring_size" : max_ring_size
}

In [11]:
prop_df = dm.descriptors.batch_compute_many_descriptors(df.mol,properties_fn=my_prop_dict,add_properties=False,
                                             progress=True)

  0%|          | 0/4042 [00:00<?, ?it/s]

In [12]:
prop_df

         mw  logp  hbd  hba  max_ring_size
0    440.18  4.63    1    5              6
1    379.17  3.68    1    5              6
2    324.15  2.52    1    5              6
3    454.28  5.09    0    6              6
4    382.14  4.89    0    4              7
...     ...   ...  ...  ...            ...
4037 493.21  3.38    2   10              6
4038 480.18  3.16    2   10              6
4039 494.19  3.81    1   10              6
4040 494.19  3.55    2   10              6
4041 494.19  3.55    2   10              6

[4042 rows x 5 columns]

In [13]:
df = pd.concat([df,prop_df],axis=1)

In [14]:
df.head()

,SMILES,Name,pIC50,IC50,mol,mw,logp,hbd,hba,max_ring_size
0,c1cc(ccc1n2cc(c3c2ccc(c3)Cl)C4CCN(CC4)CCN5CCNC...,CHEMBL12713,8.03,0.01,<rdkit.Chem.rdchem.Mol object at 0x30c31b5a0>,440.18,4.63,1,5,6
1,c1ccc2c(c1)[nH]c(=O)n2C3=CCN(CC3)CCCC(=O)c4ccc...,CHEMBL1108,7.33,0.05,<rdkit.Chem.rdchem.Mol object at 0x30c31b610>,379.17,3.68,1,5,6
2,c1ccc2c(c1)c(c[nH]2)C(=O)OC3CC4CC5CC(C3)N4CC5=O,CHEMBL2368925,5.07,8.48,<rdkit.Chem.rdchem.Mol object at 0x30c31b680>,324.15,2.52,1,5,6
3,CC(C)C(CCCN(C)CCc1ccc(c(c1)OC)OC)(C#N)c2ccc(c(...,CHEMBL6966,6.83,0.15,<rdkit.Chem.rdchem.Mol object at 0x30c31b6f0>,454.28,5.09,0,6,6
4,CCOC(=O)N1CCC(=C2c3ccc(cc3CCc4c2nccc4)Cl)CC1,CHEMBL998,6.43,0.37,<rdkit.Chem.rdchem.Mol object at 0x30c31b760>,382.14,4.89,0,4,7

In [15]:
df = df[df['mw'] <= 500]
df = df[df['logp'] <= 5]
df = df[df['hbd'] <= 5]
df = df[df['hba'] <= 10]

In [16]:
df_ro5_ok = df.query("mw <= 500 and logp <= 5 and hbd <= 5 and hba <= 10")
len(df_ro5_ok)

3477

In [17]:
df['ro5_ok'] = (df.mw <= 500) & (df.logp <=5) & (df.hbd <= 5) & (df.hba <= 10)
df.ro5_ok.sum()

np.int64(3477)

In [18]:
def bool_to_int(bool_in):
    return bool_in.values.astype(int)

In [19]:
df['ro5_count'] = bool_to_int(df.mw <= 500) + bool_to_int(df.logp <=5) + bool_to_int(df.hbd <= 5) + bool_to_int(df.hba <= 10)
len(df.query("ro5_count == 4"))

3477

In [23]:
df = df.reset_index(drop=True)
# cluster the molecules
cluster_list = dm.cluster_mols(df.mol)
# create a list to hold the cluster ids, which we will add to the dataframe
cluster_idx = [-1] * len(df)
for i,cluster in enumerate(tqdm(cluster_list[0])):
    # align the structures for each cluster using Bemis Murcko frameworks
    dm.align.auto_align_many([df.mol.values[x] for x in cluster],copy=False,partition_method='scaffold')
    # add the cluster id to cluster_idx
    for c in cluster:
        cluster_idx[c] = i
# add a column with cluster ids to the dataframe
df['cluster'] = cluster_idx

  0%|          | 0/3026 [00:00<?, ?it/s]

In [24]:
cluster_sample_df = df.sort_values("cluster").drop_duplicates("cluster").copy()
cluster_sample_df.head()

,SMILES,Name,pIC50,IC50,mol,mw,logp,hbd,hba,max_ring_size,ro5_ok,ro5_count,cluster
972,CC(C)Oc1ccc(cc1)C2CN(C(=O)N2CCc3ccc(cc3)OC)NS(...,CHEMBL571952,4.77,16.98,<rdkit.Chem.rdchem.Mol object at 0x30c36e500>,447.18,2.97,1,8,6,True,4,0
2054,c1ccc(c(c1)C(=O)Nc2ccc(cc2)c3nnc(o3)NCCCCN4CCC...,CHEMBL2022733,4.90,12.59,<rdkit.Chem.rdchem.Mol object at 0x30e40c970>,437.22,4.81,2,7,6,True,4,1
1066,Cc1c(ocn1)c2nnc(n2C)SCCCN3CC4CC4(C3)c5ccc(cc5)...,CHEMBL1079823,6.40,0.40,<rdkit.Chem.rdchem.Mol object at 0x30c3753f0>,451.24,4.83,0,6,6,True,4,2
1061,Cc1c(ocn1)c2nnc(n2C)SCCCN3CC4CC4(C3)c5ccc(cc5)Cl,CHEMBL1080490,6.39,0.41,<rdkit.Chem.rdchem.Mol object at 0x30c375150>,429.14,4.19,0,6,6,True,4,3
3358,COc1ccc(cc1)c2nnc(o2)C(=O)N3CCC(CC3)Oc4ccc(cc4...,CHEMBL3786572,4.96,10.96,<rdkit.Chem.rdchem.Mol object at 0x30e443760>,462.23,4.02,0,8,6,True,4,4

In [25]:
cluster_count_df = df.cluster.value_counts().to_frame().reset_index()
cluster_count_df.columns = ["cluster","count"]
cluster_sample_df = cluster_sample_df.merge(cluster_count_df,on="cluster")
cluster_sample_df.head()

,SMILES,Name,pIC50,IC50,mol,mw,logp,hbd,hba,max_ring_size,ro5_ok,ro5_count,cluster,count
0,CC(C)Oc1ccc(cc1)C2CN(C(=O)N2CCc3ccc(cc3)OC)NS(...,CHEMBL571952,4.77,16.98,<rdkit.Chem.rdchem.Mol object at 0x30c36e500>,447.18,2.97,1,8,6,True,4,0,10
1,c1ccc(c(c1)C(=O)Nc2ccc(cc2)c3nnc(o3)NCCCCN4CCC...,CHEMBL2022733,4.90,12.59,<rdkit.Chem.rdchem.Mol object at 0x30e40c970>,437.22,4.81,2,7,6,True,4,1,9
2,Cc1c(ocn1)c2nnc(n2C)SCCCN3CC4CC4(C3)c5ccc(cc5)...,CHEMBL1079823,6.40,0.40,<rdkit.Chem.rdchem.Mol object at 0x30c3753f0>,451.24,4.83,0,6,6,True,4,2,8
3,Cc1c(ocn1)c2nnc(n2C)SCCCN3CC4CC4(C3)c5ccc(cc5)Cl,CHEMBL1080490,6.39,0.41,<rdkit.Chem.rdchem.Mol object at 0x30c375150>,429.14,4.19,0,6,6,True,4,3,4
4,COc1ccc(cc1)c2nnc(o2)C(=O)N3CCC(CC3)Oc4ccc(cc4...,CHEMBL3786572,4.96,10.96,<rdkit.Chem.rdchem.Mol object at 0x30e443760>,462.23,4.02,0,8,6,True,4,4,7

In [26]:
mols2grid.display(cluster_sample_df,mol_col="mol",subset=["img","cluster","count"])

In [27]:
def show_cluster(x):
    return mols2grid.display(df.query(f"cluster == {x}"),mol_col="mol",subset=["img","Name","pIC50"],use_coords=True, prerender=True, transform = {"pIC50" : lambda val: f"{val:.2f}"})

In [28]:
show_cluster(1)

In [33]:
cluster_list = dm.cluster_mols(df.mol)

In [34]:
cluster_list

(((971, 966, 967, 968, 969, 970, 972, 973, 976, 977),
  (2022, 2023, 2024, 2025, 2044, 2046, 2047, 2052, 2054),
  (1063, 1044, 1051, 1052, 1059, 1064, 1066, 1068),
  (1061, 1042, 1048, 1060),
  (3358, 3356, 3357, 3359, 3360, 3363, 3364),
  (2827, 2820, 2821, 2822, 2828, 2829),
  (2050, 2051, 2060),
  (442, 414, 418, 438, 439, 440),
  (3467, 3473, 3474, 3475, 3476),
  (3347, 2178, 2179, 3341, 3346),
  (3331, 3122, 3123, 3332, 3333),
  (3321, 3312, 3315, 3318, 3323),
  (2937, 2933, 2934, 2935, 2936),
  (2868, 2865, 2869, 2871, 2873),
  (2493, 2491, 2494, 2495, 2496),
  (1799, 1796, 1797, 1798, 1800),
  (3280, 3281, 3282, 3283),
  (3197, 3175, 3189, 3195),
  (3152, 3144, 3147, 3151),
  (3067, 2927, 3064, 3066),
  (2872, 2861, 2862, 2863),
  (2567, 2560, 2565, 2566),
  (2056, 2032, 2033, 2034),
  (2039, 2040, 2041, 2057),
  (1939, 1936, 1937, 1938),
  (1680, 1151, 1155, 1676),
  (1633, 768, 769, 782),
  (1582, 1432, 1580, 1581),
  (1563, 1556, 1557, 1562),
  (1561, 1554, 1555, 1560),
  (1054, 1032, 1033, 1067),
  (832, 830, 834, 836),
  (781, 774, 775, 780),
  (579, 574, 575, 576),
  (483, 480, 481, 482),
  (435, 429, 430, 434),
  (292, 288, 290, 293),
  (3379, 3375, 3378),
  (3374,),
  (3335, 2950, 3334),
  (3328, 3329, 3330),
  (3320, 3314, 3317),
  (3293, 3292, 3294),
  (3229, 3230, 3242),
  (3171, 3169, 3170),
  (3119, 3117, 3118),
  (3034, 59, 96),
  (2903, 2900, 2902),
  (2860,),
  (2836, 2814, 2835),
  (2675, 2681, 2689),
  (2669, 2661, 2668),
  (2537, 2535, 2536),
  (2397, 2398, 2399),
  (2335, 2332, 2334),
  (2187, 2184, 2186),
  (2180,),
  (2172, 2173, 2175),
  (2076, 2074, 2075),
  (2071, 2072, 2073),
  (1931, 1929, 1930),
  (1928,),
  (1878, 1872, 1877),
  (1803, 1801, 1802),
  (1782, 1780, 1781),
  (1678, 1156, 1677),
  (1632, 599, 603),
  (1603, 1600, 1601),
  (1586, 1133, 1584),
  (1525, 1521, 1524),
  (1393, 1391, 1392),
  (1385, 1383, 1384),
  (1281, 1272, 1280),
  (1268, 1227, 1267),
  (1095, 1090, 1094),
  (1023, 1021, 1022),
  (857, 855, 856),
  (846, 847, 848),
  (743, 742, 745),
  (535, 533, 534),
  (527, 502, 526),
  (469, 468, 470),
  (437, 431, 436),
  (403, 400, 402),
  (392, 387, 388),
  (346, 344, 345),
  (333, 325, 326),
  (330, 320, 324),
  (291, 286, 289),
  (276, 275, 278),
  (163, 161, 165),
  (3468, 3464),
  (3445, 3444),
  (3425, 3424),
  (3377, 3376),
  (3371, 3370),
  (3367, 3366),
  (3338, 3337),
  (3319, 3316),
  (3313, 3309),
  (3306, 3305),
  (3266, 3265),
  (3245, 3244),
  (3236, 3217),
  (3225, 3219),
  (3211, 3004),
  (3183, 3182),
  (3149, 3142),
  (3134, 3131),
  (3094, 3093),
  (3072, 3069),
  (3049, 3048),
  (3017, 3016),
  (3015, 3014),
  (3013, 3012),
  (3007, 3006),
  (2970, 2968),
  (2890, 15),
  (2876, 2874),
  (2839, 2834),
  (2819,),
  (2808, 2803),
  (2807, 2806),
  (2792, 2791),
  (2781, 2778),
  (2780, 2779),
  (2721, 2720),
  (2715, 2153),
  (2703, 2702),
  (2701, 2697),
  (2699, 2696),
  (2691, 2690),
  (2621, 2615),
  (2618, 2616),
  (2610, 2609),
  (2607, 2606),
  (2602, 2599),
  (2578, 2574),
  (2559, 2558),
  (2539, 2538),
  (2487, 2486),
  (2455,),
  (2453, 624),
  (2437, 2436),
  (2427, 2426),
  (2378, 2377),
  (2374, 2373),
  (2369, 2368),
  (2358, 2356),
  (2330, 2329),
  (2324, 2321),
  (2323, 2320),
  (2318, 2317),
  (2302, 2300),
  (2289, 1847),
  (2287, 2286),
  (2270, 2266),
  (2268, 2267),
  (2238, 2231),
  (2226, 2225),
  (2212, 1922),
  (2202, 2201),
  (2166, 2165),
  (2161, 2160),
  (2117, 2116),
  (2108, 2106),
  (2087, 2086),
  (2080, 2079),
  (2066, 2064),
  (2065, 2063),
  (2055, 2026),
  (2053, 2021),
  (2042, 2038),
  (2037, 2035),
  (2007, 2004),
  (1999, 1998),
  (1982, 1981),
  (1980, 1979),
  (1893, 1891),
  (1876, 1871),
  (1845, 1837),
  (1828, 1827),
  (1820, 1814),
  (1819, 1813),
  (1785,),
  (1779, 1778),
  (1776, 1775),
  (1761, 1760),
  (1756, 1753),
  (1746, 1743),
  (1741, 1740),
  (1682, 1150),
  (1681, 1154),
  (1679, 1153),
  (1675, 1152),
  (1673, 1672),
  (1666, 1665),
  (1614, 1613),
  (1607, 1602),
  (1559, 1558),
  (1546, 1545),
  (1536, 1535),
  (1528, 1526),
  (1518, 1517),
  (1494, 1493),
  (1483, 1478),
  (1451, 1449),
  (1450, 1448),
  (1440, 4),
  (1438, 710),
  (1408, 456),
  (1405, 2),
  (1395, 20),
  (1390, 1389),
  (1387, 1386),
  (1380, 1379),
  (1375, 1374),
  (1358, 1347),
  (1354, 1353),
  (1348, 1346),
  (1295, 1294),
  (1286, 1273),
  (1285, 1283),
  (1260, 1259),
  (1257, 1226),
  (1251, 1225),
  (1231, 1230),
  (1229, 1228),
  (1222, 1221),
  (1202, 1200),
  (1169, 149),
  (1140, 1139),
  (1135, 1134),
  (1089, 1088),
  (1071, 270),
  (1065, 1043),
  (1056, 1035),
  (1055,),
  (1053, 1040),
  (1049, 1045),
  (1047, 1046),
  (1016, 748),
  (1013, 1012),
  (1001, 938),
  (990, 989),
  (975, 974),
  (943, 941),
  (935, 934),
  (931, 929),
  (854, 853),
  (852, 473),
  (777, 776),
  (762, 761),
  (744,),
  (736, 735),
  (730, 729),
  (722, 77),
  (715, 714),
  (709, 42),
  (693, 689),
  (692, 691),
  (688, 687),
  (647, 646),
  (616, 615),
  (601, 600),
  (586, 585),
  (567, 566),
  (539, 538),
  (537, 262),
  (532, 531),
  (491, 490),
  (461, 460),
  (459, 457),
  (455, 454),
  (443, 417),
  (433, 432),
  (423, 422),
  (420, 16),
  (406, 71),
  (393, 384),
  (373, 371),
  (359, 358),
  (348, 347),
  (329, 327),
  (318, 266),
  (316, 309),
  (304, 267),
  (284, 281),
  (283, 280),
  (282, 279),
  (269, 100),
  (255, 253),
  (233, 227),
  (213, 212),
  (175, 154),
  (158, 152),
  (142, 141),
  (119, 118),
  (78, 23),
  (76, 5),
  (74, 56),
  (69, 55),
  (68, 67),
  (51, 49),
  (43, 35),
  (41, 33),
  (29, 28),
  (3472,),
  (3471,),
  (3470,),
  (3469,),
  (3466,),
  (3465,),
  (3463,),
  (3462,),
  (3461,),
  (3460,),
  (3459,),
  (3458,),
  (3457,),
  (3456,),
  (3455,),
  (3454,),
  (3453,),
  (3452,),
  (3451,),
  (3450,),
  (3449,),
  (3448,),
  (3447,),
  (3446,),
  (3443,),
  (3442,),
  (3441,),
  (3440,),
  (3439,),
  (3438,),
  (3437,),
  (3436,),
  (3435,),
  (3434,),
  (3433,),
  (3432,),
  (3431,),
  (3430,),
  (3429,),
  (3428,),
  (3427,),
  (3426,),
  (3423,),
  (3422,),
  (3421,),
  (3420,),
  (3419,),
  (3418,),
  (3417,),
  (3416,),
  (3415,),
  (3414,),
  (3413,),
  (3412,),
  (3411,),
  (3410,),
  (3409,),
  (3408,),
  (3407,),
  (3406,),
  (3405,),
  (3404,),
  (3403,),
  (3402,),
  (3401,),
  (3400,),
  (3399,),
  (3398,),
  (3397,),
  (3396,),
  (3395,),
  (3394,),
  (3393,),
  (3392,),
  (3391,),
  (3390,),
  (3389,),
  (3388,),
  (3387,),
  (3386,),
  (3385,),
  (3384,),
  (3383,),
  (3382,),
  (3381,),
  (3380,),
  (3373,),
  (3372,),
  (3369,),
  (3368,),
  (3365,),
  (3362,),
  (3361,),
  (3355,),
  (3354,),
  (3353,),
  (3352,),
  (3351,),
  (3350,),
  (3349,),
  (3348,),
  (3345,),
  (3344,),
  (3343,),
  (3342,),
  (3340,),
  (3339,),
  (3336,),
  (3327,),
  (3326,),
  (3325,),
  (3324,),
  (3322,),
  (3311,),
  (3310,),
  (3308,),
  (3307,),
  (3304,),
  (3303,),
  (3302,),
  (3301,),
  (3300,),
  (3299,),
  (3298,),
  (3297,),
  (3296,),
  (3295,),
  (3291,),
  (3290,),
  (3289,),
  (3288,),
  (3287,),
  (3286,),
  (3285,),
  (3284,),
  (3279,),
  (3278,),
  (3277,),
  (3276,),
  (3275,),
  (3274,),
  (3273,),
  (3272,),
  (3271,),
  (3270,),
  (3269,),
  (3268,),
  (3267,),
  (3264,),
  (3263,),
  (3262,),
  (3261,),
  (3260,),
  (3259,),
  (3258,),
  (3257,),
  (3256,),
  (3255,),
  (3254,),
  (3253,),
  (3252,),
  (3251,),
  (3250,),
  (3249,),
  (3248,),
  (3247,),
  (3246,),
  (3243,),
  (3241,),
  (3240,),
  (3239,),
  (3238,),
  (3237,),
  (3235,),
  (3234,),
  (3233,),
  (3232,),
  (3231,),
  (3228,),
  (3227,),
  (3226,),
  (3224,),
  (3223,),
  (3222,),
  (3221,),
  (3220,),
  (3218,),
  (3216,),
  (3215,),
  (3214,),
  (3213,),
  (3212,),
  (3210,),
  (3209,),
  (3208,),
  (3207,),
  (3206,),
  (3205,),
  (3204,),
  (3203,),
  (3202,),
  (3201,),
  (3200,),
  (3199,),
  (3198,),
  (3196,),
  (3194,),
  (3193,),
  (3192,),
  (3191,),
  (3190,),
  (3188,),
  (3187,),
  (3186,),
  (3185,),
  (3184,),
  (3181,),
  (3180,),
  (3179,),
  (3178,),
  (3177,),
  (3176,),
  (3174,),
  (3173,),
  (3172,),
  (3168,),
  (3167,),
  (3166,),
  (3165,),
  (3164,),
  (3163,),
  (3162,),
  (3161,),
  (3160,),
  (3159,),
  (3158,),
  (3157,),
  (3156,),
  (3155,),
  (3154,),
  (3153,),
  (3150,),
  (3148,),
  (3146,),
  (3145,),
  (3143,),
  (3141,),
  (3140,),
  (3139,),
  (3138,),
  (3137,),
  (3136,),
  (3135,),
  (3133,),
  (3132,),
  (3130,),
  (3129,),
  (3128,),
  (3127,),
  (3126,),
  (3125,),
  (3124,),
  (3121,),
  (3120,),
  (3116,),
  (3115,),
  (3114,),
  (3113,),
  (3112,),
  (3111,),
  (3110,),
  (3109,),
  (3108,),
  (3107,),
  (3106,),
  (3105,),
  (3104,),
  (3103,),
  (3102,),
  (3101,),
  (3100,),
  (3099,),
  (3098,),
  (3097,),
  (3096,),
  (3095,),
  (3092,),
  (3091,),
  (3090,),
  (3089,),
  (3088,),
  (3087,),
  (3086,),
  (3085,),
  (3084,),
  (3083,),
  (3082,),
  (3081,),
  (3080,),
  (3079,),
  (3078,),
  (3077,),
  (3076,),
  (3075,),
  (3074,),
  (3073,),
  (3071,),
  (3070,),
  (3068,),
  (3065,),
  (3063,),
  (3062,),
  (3061,),
  (3060,),
  (3059,),
  (3058,),
  (3057,),
  (3056,),
  (3055,),
  (3054,),
  (3053,),
  (3052,),
  (3051,),
  (3050,),
  (3047,),
  (3046,),
  (3045,),
  (3044,),
  (3043,),
  (3042,),
  (3041,),
  (3040,),
  (3039,),
  (3038,),
  (3037,),
  (3036,),
  (3035,),
  (3033,),
  (3032,),
  (3031,),
  (3030,),
  (3029,),
  (3028,),
  (3027,),
  (3026,),
  (3025,),
  (3024,),
  (3023,),
  (3022,),
  (3021,),
  (3020,),
  (3019,),
  (3018,),
  (3011,),
  (3010,),
  (3009,),
  (3008,),
  (3005,),
  (3003,),
  (3002,),
  (3001,),
  (3000,),
  (2999,),
  (2998,),
  (2997,),
  (2996,),
  (2995,),
  (2994,),
  (2993,),
  (2992,),
  (2991,),
  (2990,),
  (2989,),
  (2988,),
  (2987,),
  (2986,),
  (2985,),
  (2984,),
  (2983,),
  (2982,),
  (2981,),
  (2980,),
  (2979,),
  (2978,),
  (2977,),
  (2976,),
  (2975,),
  (2974,),
  (2973,),
  (2972,),
  (2971,),
  (2969,),
  (2967,),
  (2966,),
  (2965,),
  (2964,),
  (2963,),
  (2962,),
  (2961,),
  (2960,),
  (2959,),
  (2958,),
  (2957,),
  (2956,),
  (2955,),
  (2954,),
  (2953,),
  (2952,),
  (2951,),
  (2949,),
  (2948,),
  (2947,),
  (2946,),
  (2945,),
  (2944,),
  (2943,),
  (2942,),
  (2941,),
  (2940,),
  (2939,),
  (2938,),
  (2932,),
  (2931,),
  (2930,),
  (2929,),
  (2928,),
  (2926,),
  (2925,),
  (2924,),
  (2923,),
  (2922,),
  (2921,),
  (2920,),
  (2919,),
  (2918,),
  (2917,),
  (2916,),
  (2915,),
  (2914,),
  (2913,),
  (2912,),
  (2911,),
  (2910,),
  (2909,),
  (2908,),
  (2907,),
  (2906,),
  (2905,),
  (2904,),
  (2901,),
  (2899,),
  (2898,),
  (2897,),
  (2896,),
  (2895,),
  (2894,),
  (2893,),
  (2892,),
  (2891,),
  (2889,),
  (2888,),
  (2887,),
  (2886,),
  (2885,),
  (2884,),
  (2883,),
  (2882,),
  (2881,),
  (2880,),
  (2879,),
  (2878,),
  (2877,),
  (2875,),
  (2870,),
  (2867,),
  (2866,),
  (2864,),
  (2859,),
  (2858,),
  (2857,),
  (2856,),
  (2855,),
  (2854,),
  (2853,),
  (2852,),
  (2851,),
  (2850,),
  (2849,),
  (2848,),
  (2847,),
  (2846,),
  (2845,),
  (2844,),
  (2843,),
  (2842,),
  (2841,),
  (2840,),
  (2838,),
  (2837,),
  (2833,),
  (2832,),
  (2831,),
  (2830,),
  (2826,),
  (2825,),
  (2824,),
  (2823,),
  (2818,),
  (2817,),
  (2816,),
  (2815,),
  (2813,),
  (2812,),
  (2811,),
  (2810,),
  (2809,),
  (2805,),
  (2804,),
  (2802,),
  (2801,),
  (2800,),
  (2799,),
  (2798,),
  (2797,),
  (2796,),
  (2795,),
  (2794,),
  (2793,),
  (2790,),
  (2789,),
  (2788,),
  (2787,),
  (2786,),
  (2785,),
  (2784,),
  (2783,),
  (2782,),
  (2777,),
  (2776,),
  (2775,),
  (2774,),
  (2773,),
  (2772,),
  (2771,),
  (2770,),
  (2769,),
  (2768,),
  (2767,),
  (2766,),
  (2765,),
  (2764,),
  (2763,),
  (2762,),
  (2761,),
  (2760,),
  (2759,),
  (2758,),
  (2757,),
  (2756,),
  (2755,),
  (2754,),
  (2753,),
  (2752,),
  (2751,),
  (2750,),
  (2749,),
  (2748,),
  (2747,),
  (2746,),
  (2745,),
  (2744,),
  (2743,),
  (2742,),
  (2741,),
  (2740,),
  (2739,),
  (2738,),
  (2737,),
  (2736,),
  (2735,),
  (2734,),
  (2733,),
  (2732,),
  (2731,),
  (2730,),
  (2729,),
  (2728,),
  (2727,),
  (2726,),
  (2725,),
  (2724,),
  (2723,),
  (2722,),
  (2719,),
  (2718,),
  (2717,),
  (2716,),
  (2714,),
  (2713,),
  (2712,),
  (2711,),
  (2710,),
  (2709,),
  (2708,),
  (2707,),
  (2706,),
  (2705,),
  (2704,),
  (2700,),
  (2698,),
  (2695,),
  (2694,),
  (2693,),
  (2692,),
  (2688,),
  (2687,),
  (2686,),
  (2685,),
  (2684,),
  (2683,),
  (2682,),
  (2680,),
  (2679,),
  (2678,),
  (2677,),
  (2676,),
  (2674,),
  (2673,),
  (2672,),
  (2671,),
  (2670,),
  (2667,),
  (2666,),
  (2665,),
  (2664,),
  (2663,),
  (2662,),
  (2660,),
  (2659,),
  (2658,),
  (2657,),
  (2656,),
  (2655,),
  (2654,),
  (2653,),
  (2652,),
  (2651,),
  (2650,),
  (2649,),
  (2648,),
  (2647,),
  (2646,),
  (2645,),
  (2644,),
  (2643,),
  (2642,),
  (2641,),
  (2640,),
  (2639,),
  (2638,),
  (2637,),
  (2636,),
  (2635,),
  (2634,),
  (2633,),
  (2632,),
  (2631,),
  (2630,),
  (2629,),
  (2628,),
  (2627,),
  (2626,),
  (2625,),
  (2624,),
  (2623,),
  (2622,),
  (2620,),
  (2619,),
  (2617,),
  (2614,),
  (2613,),
  (2612,),
  (2611,),
  (2608,),
  (2605,),
  (2604,),
  (2603,),
  (2601,),
  (2600,),
  (2598,),
  (2597,),
  (2596,),
  (2595,),
  ...),
 [(<rdkit.Chem.rdchem.Mol at 0x30c36e490>,
   <rdkit.Chem.rdchem.Mol at 0x30c36e260>,
   <rdkit.Chem.rdchem.Mol at 0x30c36e2d0>,
   <rdkit.Chem.rdchem.Mol at 0x30c36e340>,
   <rdkit.Chem.rdchem.Mol at 0x30c36e3b0>,
   <rdkit.Chem.rdchem.Mol at 0x30c36e420>,
   <rdkit.Chem.rdchem.Mol at 0x30c36e500>,
   <rdkit.Chem.rdchem.Mol at 0x30c36e570>,
   <rdkit.Chem.rdchem.Mol at 0x30c36e6c0>,
   <rdkit.Chem.rdchem.Mol at 0x30c36e730>),
  (<rdkit.Chem.rdchem.Mol at 0x30e40ba00>,
   <rdkit.Chem.rdchem.Mol at 0x30e40ba70>,
   <rdkit.Chem.rdchem.Mol at 0x30e40bae0>,
   <rdkit.Chem.rdchem.Mol at 0x30e40bb50>,
   <rdkit.Chem.rdchem.Mol at 0x30e40c510>,
   <rdkit.Chem.rdchem.Mol at 0x30e40c5f0>,
   <rdkit.Chem.rdchem.Mol at 0x30e40c660>,
   <rdkit.Chem.rdchem.Mol at 0x30e40c890>,
   <rdkit.Chem.rdchem.Mol at 0x30e40c970>),
  (<rdkit.Chem.rdchem.Mol at 0x30c3752a0>,
   <rdkit.Chem.rdchem.Mol at 0x30c3749e0>,
   <rdkit.Chem.rdchem.Mol at 0x30c374cf0>,
   <rdkit.Chem.rdchem.Mol at 0x30c374d60>,
   <rdkit.Chem.rdchem.Mol at 0x30c375070>,
   <rdkit.Chem.rdchem.Mol at 0x30c375310>,
   <rdkit.Chem.rdchem.Mol at 0x30c3753f0>,
   <rdkit.Chem.rdchem.Mol at 0x30c3754d0>),
  (<rdkit.Chem.rdchem.Mol at 0x30c375150>,
   <rdkit.Chem.rdchem.Mol at 0x30c374820>,
   <rdkit.Chem.rdchem.Mol at 0x30c374ba0>,
   <rdkit.Chem.rdchem.Mol at 0x30c3750e0>),
  (<rdkit.Chem.rdchem.Mol at 0x30e443760>,
   <rdkit.Chem.rdchem.Mol at 0x30e443680>,
   <rdkit.Chem.rdchem.Mol at 0x30e4436f0>,
   <rdkit.Chem.rdchem.Mol at 0x30e4437d0>,
   <rdkit.Chem.rdchem.Mol at 0x30e443840>,
   <rdkit.Chem.rdchem.Mol at 0x30e443990>,
   <rdkit.Chem.rdchem.Mol at 0x30e443a00>),
  (<rdkit.Chem.rdchem.Mol at 0x30e42d700>,
   <rdkit.Chem.rdchem.Mol at 0x30e42d380>,
   <rdkit.Chem.rdchem.Mol at 0x30e42d3f0>,
   <rdkit.Chem.rdchem.Mol at 0x30e42d460>,
   <rdkit.Chem.rdchem.Mol at 0x30e42d770>,
   <rdkit.Chem.rdchem.Mol at 0x30e42d7e0>),
  (<rdkit.Chem.rdchem.Mol at 0x30e40c7b0>,
   <rdkit.Chem.rdchem.Mol at 0x30e40c820>,
   <rdkit.Chem.rdchem.Mol at 0x30e40cc80>),
  (<rdkit.Chem.rdchem.Mol at 0x30c359e70>,
   <rdkit.Chem.rdchem.Mol at 0x30c359230>,
   <rdkit.Chem.rdchem.Mol at 0x30c3593f0>,
   <rdkit.Chem.rdchem.Mol at 0x30c359cb0>,
   <rdkit.Chem.rdchem.Mol at 0x30c359d20>,
   <rdkit.Chem.rdchem.Mol at 0x30c359d90>),
  (<rdkit.Chem.rdchem.Mol at 0x30e446960>,
   <rdkit.Chem.rdchem.Mol at 0x30e446c00>,
   <rdkit.Chem.rdchem.Mol at 0x30e446c70>,
   <rdkit.Chem.rdchem.Mol at 0x30e446ce0>,
   <rdkit.Chem.rdchem.Mol at 0x30e446d50>),
  (<rdkit.Chem.rdchem.Mol at 0x30e442c00>,
   <rdkit.Chem.rdchem.Mol at 0x30e410660>,
   <rdkit.Chem.rdchem.Mol at 0x30e4106d0>,
   <rdkit.Chem.rdchem.Mol at 0x30e442650>,
   <rdkit.Chem.rdchem.Mol at 0x30e442b90>),
  (<rdkit.Chem.rdchem.Mol at 0x30e4421f0>,
   <rdkit.Chem.rdchem.Mol at 0x30e437ae0>,
   <rdkit.Chem.rdchem.Mol at 0x30e437b50>,
   <rdkit.Chem.rdchem.Mol at 0x30e442260>,
   <rdkit.Chem.rdchem.Mol at 0x30e4422d0>),
  (<rdkit.Chem.rdchem.Mol at 0x30e441d90>,
   <rdkit.Chem.rdchem.Mol at 0x30e4419a0>,
   <rdkit.Chem.rdchem.Mol at 0x30e441af0>,
   <rdkit.Chem.rdchem.Mol at 0x30e441c40>,
   <rdkit.Chem.rdchem.Mol at 0x30e441e70>),
  (<rdkit.Chem.rdchem.Mol at 0x30e431930>,
   <rdkit.Chem.rdchem.Mol at 0x30e431770>,
   <rdkit.Chem.rdchem.Mol at 0x30e4317e0>,
   <rdkit.Chem.rdchem.Mol at 0x30e431850>,
   <rdkit.Chem.rdchem.Mol at 0x30e4318c0>),
  (<rdkit.Chem.rdchem.Mol at 0x30e42eb90>,
   <rdkit.Chem.rdchem.Mol at 0x30e42e960>,
   <rdkit.Chem.rdchem.Mol at 0x30e42ec00>,
   <rdkit.Chem.rdchem.Mol at 0x30e42edc0>,
   <rdkit.Chem.rdchem.Mol at 0x30e42eea0>),
  (<rdkit.Chem.rdchem.Mol at 0x30e41e1f0>,
   <rdkit.Chem.rdchem.Mol at 0x30e41e110>,
   <rdkit.Chem.rdchem.Mol at 0x30e41e260>,
   <rdkit.Chem.rdchem.Mol at 0x30e41e340>,
   <rdkit.Chem.rdchem.Mol at 0x30e41e3b0>),
  (<rdkit.Chem.rdchem.Mol at 0x30e4006d0>,
   <rdkit.Chem.rdchem.Mol at 0x30e400580>,
   <rdkit.Chem.rdchem.Mol at 0x30e4005f0>,
   <rdkit.Chem.rdchem.Mol at 0x30e400660>,
   <rdkit.Chem.rdchem.Mol at 0x30e400740>),
  (<rdkit.Chem.rdchem.Mol at 0x30e4409e0>,
   <rdkit.Chem.rdchem.Mol at 0x30e440a50>,
   <rdkit.Chem.rdchem.Mol at 0x30e440ac0>,
   <rdkit.Chem.rdchem.Mol at 0x30e440b30>),
  (<rdkit.Chem.rdchem.Mol at 0x30e43de00>,
   <rdkit.Chem.rdchem.Mol at 0x30e43d460>,
   <rdkit.Chem.rdchem.Mol at 0x30e43da80>,
   <rdkit.Chem.rdchem.Mol at 0x30e43dd20>),
  (<rdkit.Chem.rdchem.Mol at 0x30e43c9e0>,
   <rdkit.Chem.rdchem.Mol at 0x30e43c660>,
   <rdkit.Chem.rdchem.Mol at 0x30e43c7b0>,
   <rdkit.Chem.rdchem.Mol at 0x30e43c970>),
  (<rdkit.Chem.rdchem.Mol at 0x30e436030>,
   <rdkit.Chem.rdchem.Mol at 0x30e431460>,
   <rdkit.Chem.rdchem.Mol at 0x30e435ee0>,
   <rdkit.Chem.rdchem.Mol at 0x30e435fc0>),
  (<rdkit.Chem.rdchem.Mol at 0x30e42ee30>,
   <rdkit.Chem.rdchem.Mol at 0x30e42e7a0>,
   <rdkit.Chem.rdchem.Mol at 0x30e42e810>,
   <rdkit.Chem.rdchem.Mol at 0x30e42e880>),
  (<rdkit.Chem.rdchem.Mol at 0x30e420820>,
   <rdkit.Chem.rdchem.Mol at 0x30e420510>,
   <rdkit.Chem.rdchem.Mol at 0x30e420740>,
   <rdkit.Chem.rdchem.Mol at 0x30e4207b0>),
  (<rdkit.Chem.rdchem.Mol at 0x30e40ca50>,
   <rdkit.Chem.rdchem.Mol at 0x30e40be60>,
   <rdkit.Chem.rdchem.Mol at 0x30e40bed0>,
   <rdkit.Chem.rdchem.Mol at 0x30e40bf40>),
  (<rdkit.Chem.rdchem.Mol at 0x30e40c270>,
   <rdkit.Chem.rdchem.Mol at 0x30e40c2e0>,
   <rdkit.Chem.rdchem.Mol at 0x30e40c350>,
   <rdkit.Chem.rdchem.Mol at 0x30e40cac0>),
  (<rdkit.Chem.rdchem.Mol at 0x30e409310>,
   <rdkit.Chem.rdchem.Mol at 0x30e4091c0>,
   <rdkit.Chem.rdchem.Mol at 0x30e409230>,
   <rdkit.Chem.rdchem.Mol at 0x30e4092a0>),
  (<rdkit.Chem.rdchem.Mol at 0x30c38c510>,
   <rdkit.Chem.rdchem.Mol at 0x30c377ed0>,
   <rdkit.Chem.rdchem.Mol at 0x30c378120>,
   <rdkit.Chem.rdchem.Mol at 0x30c38c350>),
  (<rdkit.Chem.rdchem.Mol at 0x30c38af80>,
   <rdkit.Chem.rdchem.Mol at 0x30c3686d0>,
   <rdkit.Chem.rdchem.Mol at 0x30c368740>,
   <rdkit.Chem.rdchem.Mol at 0x30c368cf0>),
  (<rdkit.Chem.rdchem.Mol at 0x30c389930>,
   <rdkit.Chem.rdchem.Mol at 0x30c385000>,
   <rdkit.Chem.rdchem.Mol at 0x30c389850>,
   <rdkit.Chem.rdchem.Mol at 0x30c3898c0>),
  (<rdkit.Chem.rdchem.Mol at 0x30c388f90>,
   <rdkit.Chem.rdchem.Mol at 0x30c388c80>,
   <rdkit.Chem.rdchem.Mol at 0x30c388cf0>,
   <rdkit.Chem.rdchem.Mol at 0x30c388f20>),
  (<rdkit.Chem.rdchem.Mol at 0x30c388eb0>,
   <rdkit.Chem.rdchem.Mol at 0x30c388ba0>,
   <rdkit.Chem.rdchem.Mol at 0x30c388c10>,
   <rdkit.Chem.rdchem.Mol at 0x30c388e40>),
  (<rdkit.Chem.rdchem.Mol at 0x30c374e40>,
   <rdkit.Chem.rdchem.Mol at 0x30c3742e0>,
   <rdkit.Chem.rdchem.Mol at 0x30c374350>,
   <rdkit.Chem.rdchem.Mol at 0x30c375460>),
  (<rdkit.Chem.rdchem.Mol at 0x30c36a340>,
   <rdkit.Chem.rdchem.Mol at 0x30c36a260>,
   <rdkit.Chem.rdchem.Mol at 0x30c36a420>,
   <rdkit.Chem.rdchem.Mol at 0x30c36a500>),
  (<rdkit.Chem.rdchem.Mol at 0x30c368c80>,

In [36]:
len(df)

3477